//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akınsoft_Kutuphane_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitap()
        {
            this.OduncTeslim = new HashSet<OduncTeslim>();
        }
        [System.ComponentModel.DataAnnotations.Schema.NotMapped]
        public string TamAd { get; set; }
        public int KitapId { get; set; }
        public string KitapAd { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public Nullable<int> YayinYili { get; set; }
        public Nullable<int> YazarId { get; set; }
        public Nullable<int> SayfaSayisi { get; set; }
        public string AnahtarKelime { get; set; }
        public string ISBNNo { get; set; }
        public Nullable<bool> StokDurum { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Yazar Yazar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OduncTeslim> OduncTeslim { get; set; }
    }
}
